apiVersion: v1
kind: configMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: app
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: satishbandi33/user:v1
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
spec:
  scaleTargetRef:
    kind: Deployment
    name: user
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10